language: go
go:
  - "1.13.x"
  - "1.14.x"
  - "1.x"

env:
  - GO111MODULE=on GOFLAGS=-mod=readonly GOPROXY=https://proxy.golang.org

cache:
  directories:
    - $GOPATH/pkg/mod

before_install:
  - go generate ./... && git diff --exit-code; code=$?; (exit $code)
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin
  - go mod download
  - go get github.com/mattn/goveralls

script:
  - golangci-lint run ./...
  - go vet ./...
  - go test -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-ci

notifications:
  email:
    on_success: never
    on_failure: always